In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\Users\this\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\this\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\this\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\this\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\this\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
value={"name":["Malhar","Manikarnika"],"age":[22,23]}
print(value)
value

pd.Series(value)

{'name': ['Malhar', 'Manikarnika'], 'age': [22, 23]}

name    [Malhar, Manikarnika]
age                  [22, 23]
dtype: object

In [4]:
value={"name":["Malhar","Manikarnika"],"age":[22,23]}
pd.DataFrame(value)

          name  age
0       Malhar   22
1  Manikarnika   23

#reading a file in pandas

In [5]:
df=pd.read_csv("college_students.csv")
df

,Student_ID,Name,Department,Grade,Attendance (%),Semester,Result_Date,Remarks,Maths,Physics,Chemistry,Programming,Electronics,Mechanics
0,S1000,Priya,CSE,C,82,4,2023-05-23,Good,83,87,97,100,45,77
1,S1001,Ravi,CSE,A,77,4,2023-08-27,Good,75,52,85,81,84,74
2,S1002,Ravi,ECE,D,93,5,2023-01-07,Needs improvement,84,67,61,57,49,53
3,S1003,Anjali,CSE,A,87,2,2024-01-03,Excellent,78,56,91,42,86,69
4,S1004,Kiran,CSE,D,77,5,2024-10-05,Excellent,76,52,85,44,42,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,S1495,Anjali,CE,C,79,5,2023-01-11,Good,73,92,88,94,48,62
496,S1496,Mohit,CE,F,75,8,2024-05-03,Excellent,40,89,67,91,58,78
497,S1497,Sneha,CSE,F,86,4,2024-02-26,Average,65,55,50,85,87,81
498,S1498,Ravi,CE,B,83,2,2024-03-08,Needs improvement,73,88,91,98,79,91
499,S1499,Mohit,ME,F,100,5,2024-02-27,Needs improvement,94,44,51,48,58,47

Read particular no: rows from the beginning

In [6]:
df.head()
df.head(10)

,Student_ID,Name,Department,Grade,Attendance (%),Semester,Result_Date,Remarks,Maths,Physics,Chemistry,Programming,Electronics,Mechanics
0,S1000,Priya,CSE,C,82,4,2023-05-23,Good,83,87,97,100,45,77
1,S1001,Ravi,CSE,A,77,4,2023-08-27,Good,75,52,85,81,84,74
2,S1002,Ravi,ECE,D,93,5,2023-01-07,Needs improvement,84,67,61,57,49,53
3,S1003,Anjali,CSE,A,87,2,2024-01-03,Excellent,78,56,91,42,86,69
4,S1004,Kiran,CSE,D,77,5,2024-10-05,Excellent,76,52,85,44,42,82
5,S1005,Sneha,ME,A,82,2,2024-01-25,Excellent,69,80,93,63,50,63
6,S1006,Anjali,ECE,C,97,2,2024-09-15,Needs improvement,74,86,55,50,69,64
7,S1007,Mohit,IT,F,82,6,2023-02-27,Needs improvement,92,42,91,60,65,57
8,S1008,Priya,ECE,F,97,6,2023-08-06,Average,65,96,98,81,69,49
9,S1009,Mohit,ECE,B,98,5,2024-08-21,Average,97,77,65,63,54,48

Read particular no: of rows from the end

In [7]:
df.tail()
df.tail(10)

,Student_ID,Name,Department,Grade,Attendance (%),Semester,Result_Date,Remarks,Maths,Physics,Chemistry,Programming,Electronics,Mechanics
490,S1490,Priya,ECE,B,87,2,2023-04-08,Good,99,96,70,75,43,41
491,S1491,Ravi,EEE,A,78,5,2024-09-24,Needs improvement,45,81,99,96,64,59
492,S1492,Sneha,ECE,C,89,3,2023-05-15,Needs improvement,41,42,82,62,95,98
493,S1493,Anjali,CE,D,92,5,2024-07-15,Average,48,100,84,74,51,77
494,S1494,Divya,CE,F,88,5,2023-12-22,Average,74,54,91,45,68,59
495,S1495,Anjali,CE,C,79,5,2023-01-11,Good,73,92,88,94,48,62
496,S1496,Mohit,CE,F,75,8,2024-05-03,Excellent,40,89,67,91,58,78
497,S1497,Sneha,CSE,F,86,4,2024-02-26,Average,65,55,50,85,87,81
498,S1498,Ravi,CE,B,83,2,2024-03-08,Needs improvement,73,88,91,98,79,91
499,S1499,Mohit,ME,F,100,5,2024-02-27,Needs improvement,94,44,51,48,58,47

Getting infromation about a dataset

In [8]:
df=pd.read_csv("college_students.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      500 non-null    str
 1   Name            500 non-null    str
 2   Department      500 non-null    str
 3   Grade           500 non-null    str
 4   Attendance (%)  500 non-null    int64
 5   Semester        500 non-null    int64
 6   Result_Date     500 non-null    str
 7   Remarks         500 non-null    str
 8   Maths           500 non-null    int64
 9   Physics         500 non-null    int64
 10  Chemistry       500 non-null    int64
 11  Programming     500 non-null    int64
 12  Electronics     500 non-null    int64
 13  Mechanics       500 non-null    int64
dtypes: int64(8), str(6)
memory usage: 54.8 KB

Function used to describe the dataset

In [9]:
df=pd.read_csv("college_students.csv")
df.describe()

,Attendance (%),Semester,Maths,Physics,Chemistry,Programming,Electronics,Mechanics
count,500.00000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,87.71800,4.646000,69.334000,71.018000,69.824000,70.196000,69.384000,70.530000
std,7.42946,2.288922,17.232654,18.281085,16.938206,17.729361,16.922686,17.533509
min,75.00000,1.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000
25%,81.75000,3.000000,54.000000,54.000000,55.000000,55.750000,56.000000,56.000000
50%,87.00000,5.000000,69.000000,73.000000,71.000000,69.000000,69.000000,71.000000
75%,94.00000,7.000000,84.000000,87.000000,83.250000,86.000000,83.000000,86.000000
max,100.00000,8.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

Print a single column from the dataset

In [10]:
df=pd.read_csv("college_students.csv")
df["Name"]

0       Priya
1        Ravi
2        Ravi
3      Anjali
4       Kiran
        ...
495    Anjali
496     Mohit
497     Sneha
498      Ravi
499     Mohit
Name: Name, Length: 500, dtype: str

print the names of columns

In [11]:
df=pd.read_csv("college_students.csv")
df.columns

Index(['Student_ID', 'Name', 'Department', 'Grade', 'Attendance (%)',
       'Semester', 'Result_Date', 'Remarks', 'Maths', 'Physics', 'Chemistry',
       'Programming', 'Electronics', 'Mechanics'],
      dtype='str')

print multiple columns from the dataset

In [12]:
df=pd.read_csv("college_students.csv")
df[["Name","Department","Grade"]]

       Name Department Grade
0     Priya        CSE     C
1      Ravi        CSE     A
2      Ravi        ECE     D
3    Anjali        CSE     A
4     Kiran        CSE     D
..      ...        ...   ...
495  Anjali         CE     C
496   Mohit         CE     F
497   Sneha        CSE     F
498    Ravi         CE     B
499   Mohit         ME     F

[500 rows x 3 columns]

print the dimension of dataset

In [13]:
df=pd.read_csv("college_students.csv")
df.shape

(500, 14)

print the range of dataset

In [14]:
df=pd.read_csv("college_students.csv")
df.index

RangeIndex(start=0, stop=500, step=1)

print range and column name together

In [15]:
df=pd.read_csv("college_students.csv")
df.axes

[RangeIndex(start=0, stop=500, step=1),
 Index(['Student_ID', 'Name', 'Department', 'Grade', 'Attendance (%)',
        'Semester', 'Result_Date', 'Remarks', 'Maths', 'Physics', 'Chemistry',
        'Programming', 'Electronics', 'Mechanics'],
       dtype='str')]

To change the column name or giving name to unnamed columns use rename()

In [16]:
df=pd.read_csv("college_students.csv")
names={"Name":"StudentName"}
df.rename(columns=names).head()

,Student_ID,StudentName,Department,Grade,Attendance (%),Semester,Result_Date,Remarks,Maths,Physics,Chemistry,Programming,Electronics,Mechanics
0,S1000,Priya,CSE,C,82,4,2023-05-23,Good,83,87,97,100,45,77
1,S1001,Ravi,CSE,A,77,4,2023-08-27,Good,75,52,85,81,84,74
2,S1002,Ravi,ECE,D,93,5,2023-01-07,Needs improvement,84,67,61,57,49,53
3,S1003,Anjali,CSE,A,87,2,2024-01-03,Excellent,78,56,91,42,86,69
4,S1004,Kiran,CSE,D,77,5,2024-10-05,Excellent,76,52,85,44,42,82

Adding new column in dataset containing attendece>80

In [17]:
df=pd.read_csv("college_students.csv")

value=[]
for i in df["Attendance (%)"]:
    if (i>80):
        value.append(i)
    else:
        value.append(0)
df["Attendance80"]=value
df.head()

,Student_ID,Name,Department,Grade,Attendance (%),Semester,Result_Date,Remarks,Maths,Physics,Chemistry,Programming,Electronics,Mechanics,Attendance80
0,S1000,Priya,CSE,C,82,4,2023-05-23,Good,83,87,97,100,45,77,82
1,S1001,Ravi,CSE,A,77,4,2023-08-27,Good,75,52,85,81,84,74,0
2,S1002,Ravi,ECE,D,93,5,2023-01-07,Needs improvement,84,67,61,57,49,53,93
3,S1003,Anjali,CSE,A,87,2,2024-01-03,Excellent,78,56,91,42,86,69,87
4,S1004,Kiran,CSE,D,77,5,2024-10-05,Excellent,76,52,85,44,42,82,0

To identify the datatype of a column

In [18]:
df=pd.read_csv("college_students.csv")
df["Attendance (%)"].dtype
#df.tail(25)

dtype('int64')

To get the count of null values

In [19]:
df=pd.read_csv("sample.csv")
df.isnull().sum()

Name      4
Brand     1
Model     7
number    1
dtype: int64

To remove rows containing null vlues

In [20]:
df=pd.read_csv("sample.csv")
df.dropna()

    Name Brand Model  number
4   Benz   Be1    w2  3445.0
8    BMW    B1    w1    45.0
12   BMW    B1    w1    45.0

To remove particular cell contianig null values, (specify the columns having null values)

In [21]:
df=pd.read_csv("sample.csv")
df.dropna(subset=["number"])

    Name Brand Model  number
0    BMW    B1   NaN  4545.0
1   Benz   NaN    w2  5645.0
2    NaN    A1   NaN  8989.0
4   Benz   Be1    w2  3445.0
5    NaN    B1    w1    45.0
6   Benz   Be1   NaN  5656.0
7    NaN   Be1    w2  3445.0
8    BMW    B1    w1    45.0
9   Benz   Be1   NaN  5656.0
10  Benz   Be1   NaN  5656.0
11   NaN   Be1    w2  3445.0
12   BMW    B1    w1    45.0
13  Benz   Be1   NaN  5656.0
14  Benz   Be1   NaN  5656.0

TO insert a value in cell containig null values

In [22]:
df=pd.read_csv("sample.csv")
df.fillna(0)

    Name Brand Model  number
0    BMW    B1     0  4545.0
1   Benz     0    w2  5645.0
2      0    A1     0  8989.0
3    BMW    B1    w1     0.0
4   Benz   Be1    w2  3445.0
5      0    B1    w1    45.0
6   Benz   Be1     0  5656.0
7      0   Be1    w2  3445.0
8    BMW    B1    w1    45.0
9   Benz   Be1     0  5656.0
10  Benz   Be1     0  5656.0
11     0   Be1    w2  3445.0
12   BMW    B1    w1    45.0
13  Benz   Be1     0  5656.0
14  Benz   Be1     0  5656.0

In [23]:
df=pd.read_csv("sample.csv")
#df.fillna({"Name":"Audi"})
df["Name"]=df["Name"].fillna("Audi")
df
df["Brand"]=df["Brand"].fillna("Bs1")

In [24]:
data={"A":[45,23,12,18],
      "B":[67,23,12,45],
      "C":[34,12,10,56]
}
df=pd.DataFrame(data)
# df.add(5)
df["A"]=df["A"].add(5)
df

    A   B   C
0  50  67  34
1  28  23  12
2  17  12  10
3  23  45  56

function:sum(), can perform sum columwise and row wise

In [25]:
data={"A":[45,23,12,18],
      "B":[67,23,12,45],
      "C":[34,12,10,56]
}
df=pd.DataFrame(data)
print(df.sum()) #default row wise sum or df.sum(axis=0) or df.sum(axis="rows")
df.sum(axis=1)#column wise sum() or df.sum(axis="columns")

A     98
B    147
C    112
dtype: int64

0    146
1     58
2     34
3    119
dtype: int64

function sub()

In [26]:
data={"A":[45,23,12,18],
      "B":[67,23,12,45],
      "C":[34,12,10,56]
}
df=pd.DataFrame(data)
df.sub(5)

    A   B   C
0  40  62  29
1  18  18   7
2   7   7   5
3  13  40  51

function div()

In [27]:
data={"A":[45,23,12,18],
      "B":[67,23,12,45],
      "C":[34,12,10,56]
}
df=pd.DataFrame(data)
df
df.div(3)

           A          B          C
0  15.000000  22.333333  11.333333
1   7.666667   7.666667   4.000000
2   4.000000   4.000000   3.333333
3   6.000000  15.000000  18.666667

function mean()

In [28]:
data={"A":[45,23,12,18],
      "B":[67,23,12,45],
      "C":[34,12,10,56]
}
df=pd.DataFrame(data)
df
df.mean() # rowwise by default
df.mean(axis=1)#column wise

0    48.666667
1    19.333333
2    11.333333
3    39.666667
dtype: float64

function median

In [29]:
data={"A":[45,23,12,18],
      "B":[67,23,12,45],
      "C":[34,12,10,56]
}
df=pd.DataFrame(data)
print(df)
print(df.median())
df.median(axis=1)

    A   B   C
0  45  67  34
1  23  23  12
2  12  12  10
3  18  45  56
A    20.5
B    34.0
C    23.0
dtype: float64

0    45.0
1    23.0
2    12.0
3    45.0
dtype: float64

function mode()

In [30]:
data={"A":[45,23,12,18,45],
      "B":[67,23,12,45,12],
      "C":[34,12,10,56,10]
}
df=pd.DataFrame(data)
print(df)
print(df.mode())#row wise
#df.mode(axis=1)

    A   B   C
0  45  67  34
1  23  23  12
2  12  12  10
3  18  45  56
4  45  12  10
    A   B   C
0  45  12  10

to read selected data type colums from the dataset

In [31]:
df=pd.read_csv("college_students.csv")
df.head(5)
df.select_dtypes(include=["object"])

C:\Users\this\AppData\Local\Temp\ipykernel_13336\517173026.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=["object"])

    Student_ID    Name Department Grade Result_Date            Remarks
0        S1000   Priya        CSE     C  2023-05-23               Good
1        S1001    Ravi        CSE     A  2023-08-27               Good
2        S1002    Ravi        ECE     D  2023-01-07  Needs improvement
3        S1003  Anjali        CSE     A  2024-01-03          Excellent
4        S1004   Kiran        CSE     D  2024-10-05          Excellent
..         ...     ...        ...   ...         ...                ...
495      S1495  Anjali         CE     C  2023-01-11               Good
496      S1496   Mohit         CE     F  2024-05-03          Excellent
497      S1497   Sneha        CSE     F  2024-02-26            Average
498      S1498    Ravi         CE     B  2024-03-08  Needs improvement
499      S1499   Mohit         ME     F  2024-02-27  Needs improvement

[500 rows x 6 columns]

question: add new column total marks containing the sum of 6 subject and a column avg calculate the avg or mean

In [32]:
df=pd.read_csv("college_students.csv")
df.head(5)
df.columns
df.drop(["Attendance (%)","Semester"],axis=1,inplace=True)

df["Total_marks"]=df.select_dtypes(include=["number"]).sum(axis=1)
df["Average MArks"]=df.select_dtypes(include=["number"]).drop("Total_marks",axis=1).mean(axis=1)
df.head(5)

# drop column grade and re calculate grade from Average marks
df.drop(["Grade"],axis=1,inplace=True)
value=[]
for i in df["Average MArks"]:
    if(i>90):
        value.append("A")
    elif(i>80):
        value.append("B")
    elif(i>70):
        value.append("C")
    elif(i>60):
        value.append("D")
    elif(i>50):
        value.append("E")
    else:
        value.append("F")
df["Grade"]=value
df.head(15)

,Student_ID,Name,Department,Result_Date,Remarks,Maths,Physics,Chemistry,Programming,Electronics,Mechanics,Total_marks,Average MArks,Grade
0,S1000,Priya,CSE,2023-05-23,Good,83,87,97,100,45,77,489,81.500000,B
1,S1001,Ravi,CSE,2023-08-27,Good,75,52,85,81,84,74,451,75.166667,C
2,S1002,Ravi,ECE,2023-01-07,Needs improvement,84,67,61,57,49,53,371,61.833333,D
3,S1003,Anjali,CSE,2024-01-03,Excellent,78,56,91,42,86,69,422,70.333333,C
4,S1004,Kiran,CSE,2024-10-05,Excellent,76,52,85,44,42,82,381,63.500000,D
5,S1005,Sneha,ME,2024-01-25,Excellent,69,80,93,63,50,63,418,69.666667,D
6,S1006,Anjali,ECE,2024-09-15,Needs improvement,74,86,55,50,69,64,398,66.333333,D
7,S1007,Mohit,IT,2023-02-27,Needs improvement,92,42,91,60,65,57,407,67.833333,D
8,S1008,Priya,ECE,2023-08-06,Average,65,96,98,81,69,49,458,76.333333,C
9,S1009,Mohit,ECE,2024-08-21,Average,97,77,65,63,54,48,404,67.333333,D
10,S1010,Kiran,CE,2023-04-23,Needs improvement,80,50,90,83,67,78,448,74.666667,C
11,S1011,Priya,CE,2024-06-25,Excellent,75,95,100,40,83,86,479,79.833333,C
12,S1012,Priya,IT,2024-10-18,Excellent,47,58,67,50,69,40,331,55.166667,E
13,S1013,Mohit,EEE,2024-10-02,Excellent,93,80,72,78,52,49,424,70.666667,C
14,S1014,Anjali,ECE,2024-09-05,Excellent,71,41,47,99,63,96,417,69.500000,D

In [33]:
df=pd.read_csv("college_students.csv")
df.head(15)

,Student_ID,Name,Department,Grade,Attendance (%),Semester,Result_Date,Remarks,Maths,Physics,Chemistry,Programming,Electronics,Mechanics
0,S1000,Priya,CSE,C,82,4,2023-05-23,Good,83,87,97,100,45,77
1,S1001,Ravi,CSE,A,77,4,2023-08-27,Good,75,52,85,81,84,74
2,S1002,Ravi,ECE,D,93,5,2023-01-07,Needs improvement,84,67,61,57,49,53
3,S1003,Anjali,CSE,A,87,2,2024-01-03,Excellent,78,56,91,42,86,69
4,S1004,Kiran,CSE,D,77,5,2024-10-05,Excellent,76,52,85,44,42,82
5,S1005,Sneha,ME,A,82,2,2024-01-25,Excellent,69,80,93,63,50,63
6,S1006,Anjali,ECE,C,97,2,2024-09-15,Needs improvement,74,86,55,50,69,64
7,S1007,Mohit,IT,F,82,6,2023-02-27,Needs improvement,92,42,91,60,65,57
8,S1008,Priya,ECE,F,97,6,2023-08-06,Average,65,96,98,81,69,49
9,S1009,Mohit,ECE,B,98,5,2024-08-21,Average,97,77,65,63,54,48
10,S1010,Kiran,CE,A,99,1,2023-04-23,Needs improvement,80,50,90,83,67,78
11,S1011,Priya,CE,D,94,8,2024-06-25,Excellent,75,95,100,40,83,86
12,S1012,Priya,IT,F,99,5,2024-10-18,Excellent,47,58,67,50,69,40
13,S1013,Mohit,EEE,B,91,2,2024-10-02,Excellent,93,80,72,78,52,49
14,S1014,Anjali,ECE,F,99,1,2024-09-05,Excellent,71,41,47,99,63,96

function ffill()

In [34]:
df=pd.read_csv("sample.csv")
df
df.ffill()

    Name Brand Model  number
0    BMW    B1   NaN  4545.0
1   Benz    B1    w2  5645.0
2   Benz    A1    w2  8989.0
3    BMW    B1    w1  8989.0
4   Benz   Be1    w2  3445.0
5   Benz    B1    w1    45.0
6   Benz   Be1    w1  5656.0
7   Benz   Be1    w2  3445.0
8    BMW    B1    w1    45.0
9   Benz   Be1    w1  5656.0
10  Benz   Be1    w1  5656.0
11  Benz   Be1    w2  3445.0
12   BMW    B1    w1    45.0
13  Benz   Be1    w1  5656.0
14  Benz   Be1    w1  5656.0

function bfill()

In [35]:
df=pd.read_csv("sample.csv")
dd=df.ffill()
dd.bfill()
#remove null value completely by assigning value from above and below the cell

    Name Brand Model  number
0    BMW    B1    w2  4545.0
1   Benz    B1    w2  5645.0
2   Benz    A1    w2  8989.0
3    BMW    B1    w1  8989.0
4   Benz   Be1    w2  3445.0
5   Benz    B1    w1    45.0
6   Benz   Be1    w1  5656.0
7   Benz   Be1    w2  3445.0
8    BMW    B1    w1    45.0
9   Benz   Be1    w1  5656.0
10  Benz   Be1    w1  5656.0
11  Benz   Be1    w2  3445.0
12   BMW    B1    w1    45.0
13  Benz   Be1    w1  5656.0
14  Benz   Be1    w1  5656.0

remove duplicates values: drop_duplicate()

In [36]:
df=pd.read_csv("sample.csv")
df
df.drop_duplicates()

   Name Brand Model  number
0   BMW    B1   NaN  4545.0
1  Benz   NaN    w2  5645.0
2   NaN    A1   NaN  8989.0
3   BMW    B1    w1     NaN
4  Benz   Be1    w2  3445.0
5   NaN    B1    w1    45.0
6  Benz   Be1   NaN  5656.0
7   NaN   Be1    w2  3445.0
8   BMW    B1    w1    45.0

to pick up a particular row

In [37]:
df=pd.read_csv("sample.csv")
df.loc[2]
df.loc[2, "number"]
df.loc[[0,2,4]]

   Name Brand Model  number
0   BMW    B1   NaN  4545.0
2   NaN    A1   NaN  8989.0
4  Benz   Be1    w2  3445.0

method iloc[]

In [38]:
df=pd.read_csv("sample.csv")
df.iloc[2,1]

'A1'

to fetch a single value use the methid at[], iat[]-give row and column index

In [39]:
df=pd.read_csv("sample.csv")
print(df.at[0,"Brand"])
df.iat[0,1]

B1

'B1'

function applymap()[not for latest version], use map() instead

In [40]:
data={"A":[45,23,12,18],
      "B":[67,23,12,45],
      "C":[34,12,10,56]
}
df=pd.DataFrame(data)
def mul(x):
    return x*2
df.map(mul)

    A    B    C
0  90  134   68
1  46   46   24
2  24   24   20
3  36   90  112

function apply()

In [41]:
data={"A":[45,23,12,18],
      "B":[67,23,12,45],
      "C":[34,12,10,56]
}
df=pd.DataFrame(data)
def mul(x):
    return x*2
df.apply(mul)
df["A"].apply(mul)

0    90
1    46
2    24
3    36
Name: A, dtype: int64

In [42]:
df1=pd.read_csv("sample.csv")
df2=pd.read_csv("sample.csv")
pd.concat([df1,df2],ignore_index=True)

    Name Brand Model  number
0    BMW    B1   NaN  4545.0
1   Benz   NaN    w2  5645.0
2    NaN    A1   NaN  8989.0
3    BMW    B1    w1     NaN
4   Benz   Be1    w2  3445.0
5    NaN    B1    w1    45.0
6   Benz   Be1   NaN  5656.0
7    NaN   Be1    w2  3445.0
8    BMW    B1    w1    45.0
9   Benz   Be1   NaN  5656.0
10  Benz   Be1   NaN  5656.0
11   NaN   Be1    w2  3445.0
12   BMW    B1    w1    45.0
13  Benz   Be1   NaN  5656.0
14  Benz   Be1   NaN  5656.0
15   BMW    B1   NaN  4545.0
16  Benz   NaN    w2  5645.0
17   NaN    A1   NaN  8989.0
18   BMW    B1    w1     NaN
19  Benz   Be1    w2  3445.0
20   NaN    B1    w1    45.0
21  Benz   Be1   NaN  5656.0
22   NaN   Be1    w2  3445.0
23   BMW    B1    w1    45.0
24  Benz   Be1   NaN  5656.0
25  Benz   Be1   NaN  5656.0
26   NaN   Be1    w2  3445.0
27   BMW    B1    w1    45.0
28  Benz   Be1   NaN  5656.0
29  Benz   Be1   NaN  5656.0

function merge()

In [43]:
df1=pd.read_csv("student1.csv")
df2=pd.read_csv("student2.csv")
df2
#pd.merge(df1,df2,on="id")

   id    sname  sage  english  it
0   1    ruvan    13       18  19
1   2  Harshig    16       17  18

function join()

In [44]:
df1=pd.read_csv("student1.csv")
df2=pd.read_csv("student2.csv")
df1.join(df2)

     name  age  maths  Physics   id    sname  sage  english    it
0     abi   22     23       24  1.0    ruvan  13.0     18.0  19.0
1   cathy   21     18       18  2.0  Harshig  16.0     17.0  18.0
2  merlin   20     15       25  NaN      NaN   NaN      NaN   NaN
3  manika   22     24       24  NaN      NaN   NaN      NaN   NaN

function duplicated()

In [45]:
df=pd.read_csv("sample.csv")
print(df.duplicated())
df.duplicated().sum()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11     True
12     True
13     True
14     True
dtype: bool

np.int64(6)

adding prefix/suffix to the column name

In [46]:
df=pd.read_csv("sample.csv")
print(df.add_prefix("Car_"))
df.add_suffix("_of_car")

   Car_Name Car_Brand Car_Model  Car_number
0       BMW        B1       NaN      4545.0
1      Benz       NaN        w2      5645.0
2       NaN        A1       NaN      8989.0
3       BMW        B1        w1         NaN
4      Benz       Be1        w2      3445.0
5       NaN        B1        w1        45.0
6      Benz       Be1       NaN      5656.0
7       NaN       Be1        w2      3445.0
8       BMW        B1        w1        45.0
9      Benz       Be1       NaN      5656.0
10     Benz       Be1       NaN      5656.0
11      NaN       Be1        w2      3445.0
12      BMW        B1        w1        45.0
13     Benz       Be1       NaN      5656.0
14     Benz       Be1       NaN      5656.0

   Name_of_car Brand_of_car Model_of_car  number_of_car
0          BMW           B1          NaN         4545.0
1         Benz          NaN           w2         5645.0
2          NaN           A1          NaN         8989.0
3          BMW           B1           w1            NaN
4         Benz          Be1           w2         3445.0
5          NaN           B1           w1           45.0
6         Benz          Be1          NaN         5656.0
7          NaN          Be1           w2         3445.0
8          BMW           B1           w1           45.0
9         Benz          Be1          NaN         5656.0
10        Benz          Be1          NaN         5656.0
11         NaN          Be1           w2         3445.0
12         BMW           B1           w1           45.0
13        Benz          Be1          NaN         5656.0
14        Benz          Be1          NaN         5656.0

function combine()

In [47]:
s1=pd.Series([34,12,56,78])
s2=pd.Series([56,23,45,67])
s1.combine(s2,max)

0    56
1    23
2    56
3    78
dtype: int64

function combine_first()

In [48]:
s1=pd.Series([34,None,56,None])
s2=pd.Series([56,23,45,67])
s1.combine_first(s2)

0    34.0
1    23.0
2    56.0
3    67.0
dtype: float64

function max(),min()

In [49]:
df=pd.read_csv("college_students.csv")
df.columns
print(df["Programming"].max())
df["Programming"].min()

100

np.int64(40)

function idxmax()

In [50]:
df=pd.read_csv("college_students.csv")
print(df.columns)
print(df["Programming"].idxmax())
df["Programming"].idxmin()
#df.loc[42]#get the details of max value holding person
df.loc[11]

Index(['Student_ID', 'Name', 'Department', 'Grade', 'Attendance (%)',
       'Semester', 'Result_Date', 'Remarks', 'Maths', 'Physics', 'Chemistry',
       'Programming', 'Electronics', 'Mechanics'],
      dtype='str')
0

Student_ID             S1011
Name                   Priya
Department                CE
Grade                      D
Attendance (%)            94
Semester                   8
Result_Date       2024-06-25
Remarks            Excellent
Maths                     75
Physics                   95
Chemistry                100
Programming               40
Electronics               83
Mechanics                 86
Name: 11, dtype: object

function:nlargest(),nsmallest()

In [51]:
df=pd.read_csv("college_students.csv")
df.nlargest(11,"Programming")
#df.nsmallest(15,"Programming")

,Student_ID,Name,Department,Grade,Attendance (%),Semester,Result_Date,Remarks,Maths,Physics,Chemistry,Programming,Electronics,Mechanics
0,S1000,Priya,CSE,C,82,4,2023-05-23,Good,83,87,97,100,45,77
42,S1042,Divya,ECE,C,76,7,2023-01-02,Needs improvement,63,67,44,100,82,98
188,S1188,Sneha,ECE,D,91,8,2024-05-25,Excellent,71,41,45,100,65,72
228,S1228,Sneha,ME,B,96,4,2024-02-28,Excellent,57,43,75,100,77,96
253,S1253,Rahul,CE,B,98,7,2023-11-21,Excellent,46,45,40,100,59,68
258,S1258,Sneha,IT,D,94,4,2024-04-13,Good,48,59,40,100,65,61
259,S1259,Divya,CE,C,89,6,2024-03-16,Needs improvement,59,60,78,100,84,52
284,S1284,Divya,ME,F,83,3,2023-11-28,Excellent,58,76,57,100,94,72
332,S1332,Sneha,EEE,C,100,6,2024-08-28,Good,85,84,62,100,76,76
402,S1402,Amit,CSE,F,94,5,2024-06-04,Needs improvement,81,82,69,100,61,63
14,S1014,Anjali,ECE,F,99,1,2024-09-05,Excellent,71,41,47,99,63,96

to get the sample value

In [52]:
df=pd.read_csv("college_students.csv")
df.sample()
df.sample(5)

,Student_ID,Name,Department,Grade,Attendance (%),Semester,Result_Date,Remarks,Maths,Physics,Chemistry,Programming,Electronics,Mechanics
198,S1198,Priya,ECE,A,89,6,2024-03-04,Needs improvement,66,84,53,66,72,89
194,S1194,Neha,EEE,D,79,3,2023-12-02,Excellent,50,65,79,87,93,59
245,S1245,Sneha,ME,A,95,1,2023-04-06,Average,64,64,75,70,43,80
384,S1384,Divya,EEE,B,78,6,2024-12-29,Good,64,96,80,56,89,74
475,S1475,Neha,ME,F,85,8,2024-08-11,Excellent,71,51,88,98,72,57

function take()

In [53]:
df=pd.read_csv("college_students.csv")
df.loc[[3,45,12]] # method
df.take([3,45,12])# function

,Student_ID,Name,Department,Grade,Attendance (%),Semester,Result_Date,Remarks,Maths,Physics,Chemistry,Programming,Electronics,Mechanics
3,S1003,Anjali,CSE,A,87,2,2024-01-03,Excellent,78,56,91,42,86,69
45,S1045,Amit,ME,C,81,7,2024-08-16,Excellent,69,68,68,83,53,72
12,S1012,Priya,IT,F,99,5,2024-10-18,Excellent,47,58,67,50,69,40

question: get the details of students who scored max mark in the subject "programmning"

In [54]:
df=pd.read_csv("college_students.csv")
max_value=df["Programming"].max()
print(max_value)
#max_index=df["Programming"].idxmax()
#print(max_index)
value=[]
for idex, i in df["Programming"].items():
    #print(idex,i)
    if(i==max_value):
        value.append(df.loc[idex])
value_df=pd.DataFrame(value)
value_df 

#df.loc[259]

100

,Student_ID,Name,Department,Grade,Attendance (%),Semester,Result_Date,Remarks,Maths,Physics,Chemistry,Programming,Electronics,Mechanics
0,S1000,Priya,CSE,C,82,4,2023-05-23,Good,83,87,97,100,45,77
42,S1042,Divya,ECE,C,76,7,2023-01-02,Needs improvement,63,67,44,100,82,98
188,S1188,Sneha,ECE,D,91,8,2024-05-25,Excellent,71,41,45,100,65,72
228,S1228,Sneha,ME,B,96,4,2024-02-28,Excellent,57,43,75,100,77,96
253,S1253,Rahul,CE,B,98,7,2023-11-21,Excellent,46,45,40,100,59,68
258,S1258,Sneha,IT,D,94,4,2024-04-13,Good,48,59,40,100,65,61
259,S1259,Divya,CE,C,89,6,2024-03-16,Needs improvement,59,60,78,100,84,52
284,S1284,Divya,ME,F,83,3,2023-11-28,Excellent,58,76,57,100,94,72
332,S1332,Sneha,EEE,C,100,6,2024-08-28,Good,85,84,62,100,76,76
402,S1402,Amit,CSE,F,94,5,2024-06-04,Needs improvement,81,82,69,100,61,63

get()

In [55]:
df=pd.read_csv("college_students.csv")
df.get(["Name","Department"])

       Name Department
0     Priya        CSE
1      Ravi        CSE
2      Ravi        ECE
3    Anjali        CSE
4     Kiran        CSE
..      ...        ...
495  Anjali         CE
496   Mohit         CE
497   Sneha        CSE
498    Ravi         CE
499   Mohit         ME

[500 rows x 2 columns]

function filter()

In [56]:
df=pd.read_csv("college_students.csv")
df.filter(items=["Name","Department"]).head(5)
df.filter(like="N")
df.filter(like="ment").head()
df.filter(regex="nt$").head()

  Department
0        CSE
1        CSE
2        ECE
3        CSE
4        CSE

isna()

In [57]:
df=pd.read_csv("sample.csv")
df.isna()

     Name  Brand  Model  number
0   False  False   True   False
1   False   True  False   False
2    True  False   True   False
3   False  False  False    True
4   False  False  False   False
5    True  False  False   False
6   False  False   True   False
7    True  False  False   False
8   False  False  False   False
9   False  False   True   False
10  False  False   True   False
11   True  False  False   False
12  False  False  False   False
13  False  False   True   False
14  False  False   True   False

function query()

In [58]:
df=pd.read_csv("student1.csv")
df.query("age>21")

     name  age  maths  Physics
0     abi   22     23       24
3  manika   22     24       24

function where()

In [59]:
df=pd.read_csv("student1.csv")
df["age"]=df["age"].where(df["age"]>=21)
df.dropna(subset="age")

     name   age  maths  Physics
0     abi  22.0     23       24
1   cathy  21.0     18       18
3  manika  22.0     24       24

function mask()

In [60]:
df=pd.read_csv("student1.csv")
df["age"]=df["age"].mask(df["age"]>=21)
df
df.dropna(subset="age")

     name   age  maths  Physics
2  merlin  20.0     15       25

sort_values()

In [61]:
df=pd.read_csv("student1.csv")
df.sort_values("age")
df.sort_values("age",ascending=False)
#
# df.sort_index(ascending=False)

     name  age  maths  Physics
0     abi   22     23       24
3  manika   22     24       24
1   cathy   21     18       18
2  merlin   20     15       25

groupby()

In [62]:
df=pd.DataFrame(
    {"Department":["IT","HR","IT","HR","SALES"],
     "Salary":[25000,30000,28000,20000,60000]}
)
df
df.groupby("Department").Salary.mean()

Department
HR       25000.0
IT       26500.0
SALES    60000.0
Name: Salary, dtype: float64

convert pandas datatype to python data types

In [63]:
df=pd.read_csv("student1.csv")
df.dtypes
dd=df.convert_dtypes()
dd.dtypes

name       string
age         Int64
maths       Int64
Physics     Int64
dtype: object

count()

In [64]:
df["maths"].count()

np.int64(4)

function assign()

In [65]:
df=pd.DataFrame({
    "names":["abi","cathy","bob"],
    "age":[25,23,24]
})
df.assign(gender=["m","f","m"])

   names  age gender
0    abi   25      m
1  cathy   23      f
2    bob   24      m

function insert()

In [66]:
df=pd.DataFrame({
    "names":["abi","cathy","bob"],
    "age":[25,23,24]
})
df.insert(1,"gender",["m","f","m"])
df

   names gender  age
0    abi      m   25
1  cathy      f   23
2    bob      m   24

replace()

In [67]:
df=pd.DataFrame({
    "names":["abi","cathy","bob"],
    "age":[25,23,24]
})
df["names"]=df["names"].replace("abi","Sam")
df

   names  age
0    Sam   25
1  cathy   23
2    bob   24

function to_csv()

In [68]:
df=pd.read_csv("student1.csv")
df["age"]=df["age"].mask(df["age"]>=21)
df
df.dropna(subset="age",inplace=True)
df.rename({"names":"Student_name"},inplace=True)
df.to_csv("student1.modify.txt",index=False)