# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [15]:
df=pd.read_csv("u.user",sep="|")
df.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

### Step 3. Assign it to a variable called users.

In [35]:
users=df
users.head()
users.info()
users.columns
users.axes

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    str
 3   occupation  943 non-null    str
 4   zip_code    943 non-null    str
dtypes: int64(2), str(3)
memory usage: 37.0 KB

[RangeIndex(start=0, stop=943, step=1),
 Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='str')]

In [17]:
users.head(10)

   user_id  age gender     occupation zip_code
0        1   24      M     technician    85711
1        2   53      F          other    94043
2        3   23      M         writer    32067
3        4   24      M     technician    43537
4        5   33      F          other    15213
5        6   42      M      executive    98101
6        7   57      M  administrator    91344
7        8   36      M  administrator    05201
8        9   29      M        student    01002
9       10   53      M         lawyer    90703

### Step 4. Discover what is the mean age per occupation

In [44]:
user_group_occ=users.groupby("occupation").age.mean().reset_index()

user_group_occ

       occupation        age
0   administrator  38.746835
1          artist  31.392857
2          doctor  43.571429
3        educator  42.010526
4        engineer  36.388060
5   entertainment  29.222222
6       executive  38.718750
7      healthcare  41.562500
8       homemaker  32.571429
9          lawyer  36.750000
10      librarian  40.000000
11      marketing  37.615385
12           none  26.555556
13          other  34.523810
14     programmer  33.121212
15        retired  63.071429
16       salesman  35.666667
17      scientist  35.548387
18        student  22.081633
19     technician  33.148148
20         writer  36.311111

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [93]:
# users_male=users[users.gender=="M"]
# users_male=users_male[["occupation","gender"]]
users["Male"]=users.gender=="M"
users.groupby("occupation")["Male"].mean().sort_values(ascending=False).reset_index(name="male_ratio")

       occupation  male_ratio
0          doctor    1.000000
1        engineer    0.970149
2      technician    0.962963
3         retired    0.928571
4      programmer    0.909091
5       executive    0.906250
6       scientist    0.903226
7   entertainment    0.888889
8          lawyer    0.833333
9        salesman    0.750000
10       educator    0.726316
11        student    0.693878
12          other    0.657143
13      marketing    0.615385
14         writer    0.577778
15           none    0.555556
16  administrator    0.544304
17         artist    0.535714
18      librarian    0.431373
19     healthcare    0.312500
20      homemaker    0.142857

### Step 6. For each occupation, calculate the minimum and maximum ages

In [101]:
users.groupby("occupation")["age"].agg(["min","max"]).reset_index()

       occupation  min  max
0   administrator   21   70
1          artist   19   48
2          doctor   28   64
3        educator   23   63
4        engineer   22   70
5   entertainment   15   50
6       executive   22   69
7      healthcare   22   62
8       homemaker   20   50
9          lawyer   21   53
10      librarian   23   69
11      marketing   24   55
12           none   11   55
13          other   13   64
14     programmer   20   63
15        retired   51   73
16       salesman   18   66
17      scientist   23   55
18        student    7   42
19     technician   21   55
20         writer   18   60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [115]:
user_grp_gender_occ=users.groupby(["occupation","gender"]).age.mean().reset_index(name="mean_age")
user_grp_gender_occ=pd.DataFrame(user_grp_gender_occ)
user_grp_gender_occ

       occupation gender   mean_age
0   administrator      F  40.638889
1   administrator      M  37.162791
2          artist      F  30.307692
3          artist      M  32.333333
4          doctor      M  43.571429
5        educator      F  39.115385
6        educator      M  43.101449
7        engineer      F  29.500000
8        engineer      M  36.600000
9   entertainment      F  31.000000
10  entertainment      M  29.000000
11      executive      F  44.000000
12      executive      M  38.172414
13     healthcare      F  39.818182
14     healthcare      M  45.400000
15      homemaker      F  34.166667
16      homemaker      M  23.000000
17         lawyer      F  39.500000
18         lawyer      M  36.200000
19      librarian      F  40.000000
20      librarian      M  40.000000
21      marketing      F  37.200000
22      marketing      M  37.875000
23           none      F  36.500000
24           none      M  18.600000
25          other      F  35.472222
26          other      M  34.028986
27     programmer      F  32.166667
28     programmer      M  33.216667
29        retired      F  70.000000
30        retired      M  62.538462
31       salesman      F  27.000000
32       salesman      M  38.555556
33      scientist      F  28.333333
34      scientist      M  36.321429
35        student      F  20.750000
36        student      M  22.669118
37     technician      F  38.000000
38     technician      M  32.961538
39         writer      F  37.631579
40         writer      M  35.346154

### Step 8.  For each occupation present the percentage of women and men

In [146]:
users["Male"]=users["gender"]=="M"
users["Female"]=users["gender"]=="F"
users
# total_age=users["age"].sum()
# print(total_age)
users["Male"]=users["gender"]=="M"
users["Female"]=users["gender"]=="F"
user_male_female_per=users.groupby("occupation")[["Male","Female"]].mean()*100
user_male_female_per

                     Male     Female
occupation
administrator   54.430380  45.569620
artist          53.571429  46.428571
doctor         100.000000   0.000000
educator        72.631579  27.368421
engineer        97.014925   2.985075
entertainment   88.888889  11.111111
executive       90.625000   9.375000
healthcare      31.250000  68.750000
homemaker       14.285714  85.714286
lawyer          83.333333  16.666667
librarian       43.137255  56.862745
marketing       61.538462  38.461538
none            55.555556  44.444444
other           65.714286  34.285714
programmer      90.909091   9.090909
retired         92.857143   7.142857
salesman        75.000000  25.000000
scientist       90.322581   9.677419
student         69.387755  30.612245
technician      96.296296   3.703704
writer          57.777778  42.222222

Empty DataFrame
Columns: [user_id, age, gender, occupation, zip_code, Male, Female, doc]
Index: []